global:
  scrape_interval: 5s

scrape_configs:
  - job_name: ticketing
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["backend:8080"]

  - job_name: rabbitmq
    metrics_path: /metrics
    static_configs:
      - targets: ["rabbitmq:15692"]
